name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^4.0.3
  http: ^0.12.1
  flutter_spinkit: ^4.1.2+1
  rflutter_alert: ^1.0.3
  weather_icons: ^2.0.1
  carousel_slider: ^2.2.1
  geolocation: ^1.1.2
  cupertino_icons: ^0.1.2
  clay_containers: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
        - asset: fonts/Oswald-Light.ttf
        - asset: fonts/Oswald-ExtraLight.ttf
